AllCops:
  Exclude:
    - vendor/**
    - bin/**

Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false

CyclomaticComplexity:
  Exclude:
    - providers/user.rb

MethodLength:
  Exclude:
    - providers/user.rb
