AllCops:
  Exclude:
    - vendor/**/*
    - bin/**

Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
Style/Next:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
CyclomaticComplexity:
  Exclude:
    - providers/user.rb

Metrics/AbcSize:
  Exclude:
    - providers/user.rb

MethodLength:
  Exclude:
    - providers/user.rb
